services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - public_media:/data/gdemo/public_media:rw
      - private_media:/data/gdemo/private_media:rw
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gdemoe}
      POSTGRES_USER: ${POSTGRES_USER:-gdemoe}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gdemoe}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg_data:
  public_media:
    driver_opts:
      type: cifs
      o: username=esp,password=Sergey2704,rw,uid=0,gid=0,file_mode=0777,dir_mode=0777,noperm
      device: //nas/public/data/gdemo/media
  private_media:
    driver_opts:
      type: cifs
      o: username=esp,password=Sergey2704,rw,uid=0,gid=0,file_mode=0777,dir_mode=0777,noperm
      device: //nas/esp/data/gdemo/media
